In [6]:
import pandas as pd
import yfinance as yf

def get_january_trifecta_data(start_year, end_year):
    # Download historical data for the S&P 500 Index
    sp500 = yf.download('^GSPC', start=f'{start_year}-01-01', end=f'{end_year}-12-31', progress=False)
    sp500['Year'] = sp500.index.year
    sp500['Month'] = sp500.index.month
    sp500['Day'] = sp500.index.day

    # Initialize empty lists to store data
    years, sc_rally, ffd, jb, last_11_months, full_year = [], [], [], [], [], []
    years_inverted, sc_rally_inverted, ffd_inverted, jb_inverted, last_11_months_inverted, full_year_inverted = [], [], [], [], [], []
    
    for year in range(start_year, end_year + 1):
        # Get data for the last 5 trading days of December
        last_5_december = sp500[(sp500['Year'] == year - 1) & (sp500['Month'] == 12)].tail(6)
        # Get data for the first 2 trading days of January
        first_2_january = sp500[(sp500['Year'] == year) & (sp500['Month'] == 1)].head(2)
        # Get data for the first 5 trading days of January
        first_5_january = sp500[(sp500['Year'] == year) & (sp500['Month'] == 1)].head(5)
        # Get data for the entire month of January
        entire_january = sp500[(sp500['Year'] == year) & (sp500['Month'] == 1)]
        
        # Combine last 5 trading days of December and first 2 trading days of January for Santa Claus Rally
        santa_claus_period = pd.concat([last_5_december, first_2_january])
        
        # Calculate the returns for each period if there are enough trading days
        if len(santa_claus_period) >= 7 and len(first_5_january) >= 5 and len(entire_january) > 0:
            sc_rally_return = (santa_claus_period.iloc[-1]['Close'] - santa_claus_period.iloc[0]['Close']) / santa_claus_period.iloc[0]['Close']
            ffd_return = (first_5_january.iloc[-1]['Close'] - last_5_december.iloc[-1]['Close']) / last_5_december.iloc[-1]['Close']
            jb_return = (entire_january.iloc[-1]['Close'] - last_5_december.iloc[-1]['Close']) / last_5_december.iloc[-1]['Close']
            last_11_months_return = (sp500[sp500['Year'] == year].iloc[-1]['Close'] - entire_january.iloc[-1]['Close']) / entire_january.iloc[-1]['Close']
            full_year_return = (sp500[sp500['Year'] == year].iloc[-1]['Close'] - last_5_december.iloc[-1]['Close']) / last_5_december.iloc[-1]['Close']
            
            # Check if all three conditions are met
            if sc_rally_return > 0 and ffd_return > 0 and jb_return > 0:
                years.append(year)
                sc_rally.append(sc_rally_return)
                ffd.append(ffd_return)
                jb.append(jb_return)
                last_11_months.append(last_11_months_return)
                full_year.append(full_year_return)

            
            if sc_rally_return < 0 and ffd_return < 0 and jb_return < 0:
                # store restult for every year regardless
                years_inverted.append(year)
                sc_rally_inverted.append(sc_rally_return)
                ffd_inverted.append(ffd_return)
                jb_inverted.append(jb_return)
                last_11_months_inverted.append(last_11_months_return)
                full_year_inverted.append(full_year_return)
                


    # Create a Pandas DataFrame to store the results
    trifecta_data = pd.DataFrame({
        'Year': years,
        'SC Rally': sc_rally,
        'FFD': ffd,
        'JB': jb,
        'Last 11 Months': last_11_months,
        'Full Year': full_year
    })

    all_data = pd.DataFrame({
        'Year': years_inverted,
        'SC Rally': sc_rally_inverted,
        'FFD': ffd_inverted,
        'JB': jb_inverted,
        'Last 11 Months': last_11_months_inverted,
        'Full Year': full_year_inverted
    })

    return trifecta_data, all_data

trifecta_data, all_data = get_january_trifecta_data(1950, 2023)

In [9]:
trifecta_data

    Year  SC Rally       FFD        JB  Last 11 Months  Full Year
0   1951  0.035536  0.027900  0.060206        0.097415   0.163485
1   1952  0.015738  0.002103  0.015566        0.100663   0.117796
2   1954  0.016606  0.004837  0.051189        0.379601   0.450222
3   1958  0.035208  0.025006  0.042761        0.323981   0.380595
4   1959  0.036306  0.003441  0.004347        0.080072   0.084767
5   1961  0.016902  0.012046  0.063156        0.158142   0.231286
6   1963  0.017241  0.025990  0.049128        0.133233   0.188906
7   1964  0.022897  0.013063  0.026926        0.100078   0.129699
8   1965  0.005704  0.007316  0.033156        0.055619   0.090619
9   1966  0.000759  0.007681  0.004869       -0.135121  -0.130910
10  1971  0.018868  0.000434  0.040477        0.064768   0.107868
11  1972  0.013401  0.013518  0.018121        0.135751   0.156333
12  1975  0.072013  0.021587  0.122812        0.171603   0.315490
13  1976  0.043390  0.048675  0.118306        0.065437   0.191485
14  1979  0.032626  0.027989  0.039746        0.080156   0.123088
15  1983  0.011738  0.032281  0.033134        0.135100   0.172710
16  1987  0.023748  0.062394  0.131767       -0.098511   0.020275
17  1989  0.009246  0.011738  0.071115        0.188019   0.272505
18  1995  0.002241  0.003397  0.024278        0.309319   0.341107
19  1996  0.017740  0.004108  0.032617        0.164649   0.202637
20  1997  0.001486  0.010354  0.061317        0.234393   0.310082
21  1999  0.013219  0.037308  0.041009        0.148174   0.195260
22  2004  0.023905  0.017987  0.017276        0.071424   0.089935
23  2006  0.004211  0.033534  0.025467        0.107978   0.136194
24  2011  0.010686  0.011021  0.022646       -0.022175  -0.000032
25  2012  0.018581  0.018368  0.043583        0.086695   0.134057
26  2013  0.020431  0.021708  0.050428        0.233795   0.296012
27  2017  0.004330  0.013431  0.017884        0.173217   0.194200
28  2018  0.010612  0.027715  0.056179       -0.112245  -0.062373
29  2019  0.012939  0.026950  0.078684        0.194771   0.288781
30  2023  0.008000  0.013697  0.061753        0.012172   0.074676

In [8]:
#Write trifecta data to csv
trifecta_data.to_csv("trifecta.csv")

In [10]:
all_data

   Year  SC Rally       FFD        JB  Last 11 Months  Full Year
0  1956 -0.009029 -0.021328 -0.036500        0.065039   0.026165
1  1969 -0.011596 -0.029463 -0.008184       -0.106300  -0.113615
2  1978 -0.002985 -0.046898 -0.061514        0.076863   0.010620
3  1982 -0.018478 -0.024480 -0.017544        0.168106   0.147613
4  2000 -0.040402 -0.018908 -0.050904       -0.053196  -0.101392
5  2005 -0.018246 -0.021231 -0.025290        0.056736   0.030010
6  2008 -0.025127 -0.053236 -0.061163       -0.344783  -0.384858
7  2016 -0.023049 -0.059645 -0.050735        0.153893   0.095350